spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置Git仓库位置
          uri: https://github.com/ulei0343/codecloud.git
          # 配置仓库路径下的相对搜索位置， 可以配置多个
          search-paths: code-config-server
          # 访问 Git 仓库的用户名
          username: ulei0343
          # 访问 Git 仓库的用户密码
          password: *******
server:
  port: 20501
