server:
  port: 8081
encrypt:
  key: Hd5+dZ7ZHijwcA/ZmnSQBg==
  debug: false
spring:
  application:
    name: code-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  mail:
    host: smtp.exmail.qq.com
    username: admin@codecloud.club
    password: 123456
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: 192.168.1.103
    port: 64454
    password:
    database: 0
    jedis:
      pool:
        max-active: 1000
        max-idle: 200
        min-idle: 50
        max-wait: 1s
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.81:3308/p2p_tempdb?useUnicode=true&amp;characterEncoding=utf8&allowMultiQueries=true&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&useSSL=false
      username: operation_w
      password: hzoper@12ation
      type: com.alibaba.druid.pool.DruidDataSource
      maxActive: 1000
      initialSize: 10
      maxWait: 3000
      minIdle: 50
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        allow:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
mybatis:
  type-aliases-package: club.codecloud.demo.entity
  mapper-locations: classpath:mapper/*.xml
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 100
      expireAfterWriteInMillis: 600000
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 192.168.1.103
      port: 64454
      database: 0
