server:
  port: 9001
eureka:
  instance:
    hostname: eureka.codecloud.club
    instance-id: http://${eureka.instance.hostname}:${server.port}
  client:
    # 默认情况下，应用会向注册中心（也是它自己）注册它自己，设置为false表示禁止这种默认行为
    register-with-eureka: false
    # 表示不去检索其他的Eureka Server获取注册信息，因为服务注册中心本身的职责就是维护服务实例，它也不需要去检索其他服务
    fetch-registry: false
    service-url:
       # 对外暴露的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
