server:
  port: 10001
spring:
  mail:
    host: smtp.163.com
    username: admin@163.com
    password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接密码（默认为空
    password:
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka